version: '3'
services: 
  app:
    build: .
    depends_on: 
      - postgres
    volumes: 
#      - .:/forcegres/
      - /forcegres/node_modules
  postgres:
    image: postgres:latest
    ports:
      - "35432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=postgres
